/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'font-families': FontFamily;
    themes: Theme;
    pages: Page;
    authors: Author;
    categories: Category;
    publications: Publication;
    'theory-publications': TheoryPublication;
    'success-stories': SuccessStory;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'font-families': FontFamiliesSelect<false> | FontFamiliesSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'theory-publications': TheoryPublicationsSelect<false> | TheoryPublicationsSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'blog-settings': BlogSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'blog-settings': BlogSettingsSelect<false> | BlogSettingsSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  caption?: string | null;
  video?: {
    url?: string | null;
    poster?: (number | null) | Media;
    transcript?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font-families".
 */
export interface FontFamily {
  id: number;
  name: string;
  cssFamily: string;
  fallback: string;
  files?:
    | {
        file: number | Media;
        weight: string;
        style?: ('normal' | 'italic') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  colors: {
    paper: string;
    paper2: string;
    ink: string;
    ink2: string;
    rule: string;
    canvasDark: string;
    onDark: string;
    accent: string;
    accentStrong: string;
    accentInk: string;
    focus: string;
    success: string;
    danger: string;
    collector: string;
    magnet: string;
    forge: string;
    dataforge: string;
  };
  typography?: {
    display?: (number | null) | FontFamily;
    body?: (number | null) | FontFamily;
    mono?: (number | null) | FontFamily;
    heroScale?: number | null;
    bodyScale?: number | null;
  };
  shape?: {
    radiusInput?: number | null;
    radiusCard?: number | null;
    radiusPanel?: number | null;
    ruleWidth?: number | null;
  };
  motion?: {
    fast?: number | null;
    base?: number | null;
    slow?: number | null;
    easing?: ('standard' | 'expressive' | 'linear') | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Locale-neutral editor label. This does not appear on the website.
   */
  adminTitle: string;
  /**
   * Stable migration key; not shown in URLs.
   */
  sourceKey?: string | null;
  migrationStatus?: ('pending' | 'parity-review' | 'complete') | null;
  migrationVersion?: string | null;
  sourceHash?: string | null;
  legacySource?: string | null;
  title: string;
  /**
   * Localized path without locale prefix, e.g. 'platform' (EN) / 'plattform' (DE). Nested paths are allowed.
   */
  slug: string;
  pageType?: ('standard' | 'home' | 'platform' | 'thinking' | 'theory' | 'company' | 'legal' | 'conversion') | null;
  /**
   * Optional override; otherwise Site Settings default is used.
   */
  theme?: (number | null) | Theme;
  layout: (
    | HeroBlock
    | HeroMediaBlock
    | ProseBlock
    | FeatureGridBlock
    | CardGridBlock
    | FAQBlock
    | TimelineBlock
    | PeopleBlock
    | AwardsProofBlock
    | LinkListBlock
    | OutcomeListBlock
    | RelatedPagesBlock
    | SectionNavigationBlock
    | StatementBlock
    | MediaBlock
    | LeadFormBlock
    | RealityCheckBlock
    | CategoryEvolutionBlock
    | CapabilityJourneyBlock
    | TrustLogosBlock
    | BrandIllustrationBlock
    | TheoryReaderBlock
    | SuccessStoriesBlock
    | CTABlock
  )[];
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Locale-specific social preview image.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Mark only after a human has reviewed this locale.
   */
  translationComplete?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  primaryCta: {
    type: 'internal' | 'external';
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'publications';
          value: number | Publication;
        } | null);
    url?: string | null;
    newTab?: boolean | null;
  };
  secondaryCta: {
    type: 'internal' | 'external';
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'publications';
          value: number | Publication;
        } | null);
    url?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  /**
   * Locale-neutral editor label. This does not appear on the website.
   */
  adminTitle: string;
  title: string;
  slug: string;
  /**
   * Stable identifier from the original source; used for idempotent imports.
   */
  sourceId?: string | null;
  excerpt: string;
  /**
   * e.g. '5 min read' / '5 Min. Lesezeit'.
   */
  readingTime?: string | null;
  category?: (number | null) | Category;
  authors?: (number | Author)[] | null;
  publishedAt?: string | null;
  theme?: (number | null) | Theme;
  heroImage?: (number | null) | Media;
  /**
   * Legacy hero image path (e.g. /blog/...). Used until media is migrated to Blob.
   */
  heroImageUrl?: string | null;
  heroImageAlt?: string | null;
  /**
   * Structured body for natively-authored posts. Optional when bodyHtml is set.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Imported/legacy HTML body. Rendered as-is when the richText body is empty.
   */
  bodyHtml?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  translationComplete?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL-safe identifier, e.g. organizational-intelligence.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * e.g. Managing Director
   */
  role?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  linkedin?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroMediaBlock".
 */
export interface HeroMediaBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  media?: (number | null) | Media;
  legacyImageUrl?: string | null;
  alt?: string | null;
  primaryCta: {
    type: 'internal' | 'external';
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'publications';
          value: number | Publication;
        } | null);
    url?: string | null;
    newTab?: boolean | null;
  };
  secondaryCta: {
    type: 'internal' | 'external';
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'publications';
          value: number | Publication;
        } | null);
    url?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroMedia';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock".
 */
export interface ProseBlock {
  eyebrow?: string | null;
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'prose';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        title: string;
        copy?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  cards?:
    | {
        title: string;
        copy?: string | null;
        image?: (number | null) | Media;
        legacyImageUrl?: string | null;
        imageAlt?: string | null;
        link: {
          type: 'internal' | 'external';
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'publications';
                value: number | Publication;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        kind?: ('standard' | 'evidence' | 'capability' | 'resource') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  eyebrow?: string | null;
  heading?: string | null;
  milestones?:
    | {
        date: string;
        title: string;
        copy?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleBlock".
 */
export interface PeopleBlock {
  eyebrow?: string | null;
  heading?: string | null;
  people?:
    | {
        name: string;
        role?: string | null;
        bio?: string | null;
        image?: (number | null) | Media;
        legacyImageUrl?: string | null;
        profileLink: {
          type: 'internal' | 'external';
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'publications';
                value: number | Publication;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'people';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardsProofBlock".
 */
export interface AwardsProofBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        title: string;
        issuer?: string | null;
        year?: string | null;
        evidence?: string | null;
        logo?: (number | null) | Media;
        legacyImageUrl?: string | null;
        sourceLink: {
          type: 'internal' | 'external';
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'publications';
                value: number | Publication;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'awardsProof';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkListBlock".
 */
export interface LinkListBlock {
  eyebrow?: string | null;
  heading?: string | null;
  links?:
    | {
        link: {
          type: 'internal' | 'external';
          label: string;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'publications';
                value: number | Publication;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'linkList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OutcomeListBlock".
 */
export interface OutcomeListBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        title?: string | null;
        copy: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'outcomeList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedPagesBlock".
 */
export interface RelatedPagesBlock {
  eyebrow?: string | null;
  heading?: string | null;
  pages?: (number | Page)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedPages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionNavigationBlock".
 */
export interface SectionNavigationBlock {
  items?:
    | {
        label: string;
        anchor: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionNavigation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock".
 */
export interface StatementBlock {
  eyebrow?: string | null;
  heading: string;
  copy?: string | null;
  tone?: ('light' | 'dark' | 'accent') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  eyebrow?: string | null;
  heading?: string | null;
  image?: (number | null) | Media;
  videoUrl?: string | null;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'media';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock".
 */
export interface LeadFormBlock {
  eyebrow?: string | null;
  heading: string;
  copy?: string | null;
  buttonLabel?: string | null;
  topic?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealityCheckBlock".
 */
export interface RealityCheckBlock {
  heading?: string | null;
  copy?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'realityCheck';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryEvolutionBlock".
 */
export interface CategoryEvolutionBlock {
  heading?: string | null;
  copy?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryEvolution';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityJourneyBlock".
 */
export interface CapabilityJourneyBlock {
  heading?: string | null;
  copy?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'capabilityJourney';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustLogosBlock".
 */
export interface TrustLogosBlock {
  heading?: string | null;
  copy?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustLogos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandIllustrationBlock".
 */
export interface BrandIllustrationBlock {
  heading?: string | null;
  copy?: string | null;
  variant: 'BC-001' | 'BC-002' | 'BC-005';
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandIllustration';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TheoryReaderBlock".
 */
export interface TheoryReaderBlock {
  heading?: string | null;
  copy?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'theoryReader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SuccessStoriesBlock".
 */
export interface SuccessStoriesBlock {
  heading?: string | null;
  copy?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'successStories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  eyebrow?: string | null;
  heading: string;
  copy?: string | null;
  primaryCta: {
    type: 'internal' | 'external';
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'publications';
          value: number | Publication;
        } | null);
    url?: string | null;
    newTab?: boolean | null;
  };
  secondaryCta: {
    type: 'internal' | 'external';
    label?: string | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'publications';
          value: number | Publication;
        } | null);
    url?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theory-publications".
 */
export interface TheoryPublication {
  id: number;
  adminTitle: string;
  title: string;
  version?: string | null;
  edition?: string | null;
  readingTime?: string | null;
  chapters: {
    slug: string;
    title: string;
    blocks: {
      type: 'paragraph' | 'quote' | 'model';
      text?: string | null;
      lines?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  sourceProvenance?: string | null;
  translationComplete?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  customer: string;
  industry?: string | null;
  slug: string;
  challenge: string;
  action: string;
  result: string;
  /**
   * Only verified metrics or quotes. Leave empty if none exist.
   */
  proofPoints?:
    | {
        metric?: string | null;
        label?: string | null;
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  topic?: string | null;
  message?: string | null;
  /**
   * Form/route the lead came from, e.g. /live-demo/kontakt.
   */
  source?: string | null;
  /**
   * Explicit consent captured at submission time.
   */
  consent: boolean;
  /**
   * Exact consent copy shown to the user (audit trail).
   */
  consentText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'font-families';
        value: number | FontFamily;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'theory-publications';
        value: number | TheoryPublication;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  video?:
    | T
    | {
        url?: T;
        poster?: T;
        transcript?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font-families_select".
 */
export interface FontFamiliesSelect<T extends boolean = true> {
  name?: T;
  cssFamily?: T;
  fallback?: T;
  files?:
    | T
    | {
        file?: T;
        weight?: T;
        style?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  colors?:
    | T
    | {
        paper?: T;
        paper2?: T;
        ink?: T;
        ink2?: T;
        rule?: T;
        canvasDark?: T;
        onDark?: T;
        accent?: T;
        accentStrong?: T;
        accentInk?: T;
        focus?: T;
        success?: T;
        danger?: T;
        collector?: T;
        magnet?: T;
        forge?: T;
        dataforge?: T;
      };
  typography?:
    | T
    | {
        display?: T;
        body?: T;
        mono?: T;
        heroScale?: T;
        bodyScale?: T;
      };
  shape?:
    | T
    | {
        radiusInput?: T;
        radiusCard?: T;
        radiusPanel?: T;
        ruleWidth?: T;
      };
  motion?:
    | T
    | {
        fast?: T;
        base?: T;
        slow?: T;
        easing?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  adminTitle?: T;
  sourceKey?: T;
  migrationStatus?: T;
  migrationVersion?: T;
  sourceHash?: T;
  legacySource?: T;
  title?: T;
  slug?: T;
  pageType?: T;
  theme?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        heroMedia?: T | HeroMediaBlockSelect<T>;
        prose?: T | ProseBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        people?: T | PeopleBlockSelect<T>;
        awardsProof?: T | AwardsProofBlockSelect<T>;
        linkList?: T | LinkListBlockSelect<T>;
        outcomeList?: T | OutcomeListBlockSelect<T>;
        relatedPages?: T | RelatedPagesBlockSelect<T>;
        sectionNavigation?: T | SectionNavigationBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        media?: T | MediaBlockSelect<T>;
        leadForm?: T | LeadFormBlockSelect<T>;
        realityCheck?: T | RealityCheckBlockSelect<T>;
        categoryEvolution?: T | CategoryEvolutionBlockSelect<T>;
        capabilityJourney?: T | CapabilityJourneyBlockSelect<T>;
        trustLogos?: T | TrustLogosBlockSelect<T>;
        brandIllustration?: T | BrandIllustrationBlockSelect<T>;
        theoryReader?: T | TheoryReaderBlockSelect<T>;
        successStories?: T | SuccessStoriesBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  translationComplete?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  primaryCta?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        newTab?: T;
      };
  secondaryCta?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroMediaBlock_select".
 */
export interface HeroMediaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  media?: T;
  legacyImageUrl?: T;
  alt?: T;
  primaryCta?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        newTab?: T;
      };
  secondaryCta?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock_select".
 */
export interface ProseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        copy?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  cards?:
    | T
    | {
        title?: T;
        copy?: T;
        image?: T;
        legacyImageUrl?: T;
        imageAlt?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        kind?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  milestones?:
    | T
    | {
        date?: T;
        title?: T;
        copy?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleBlock_select".
 */
export interface PeopleBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  people?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        image?: T;
        legacyImageUrl?: T;
        profileLink?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardsProofBlock_select".
 */
export interface AwardsProofBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        issuer?: T;
        year?: T;
        evidence?: T;
        logo?: T;
        legacyImageUrl?: T;
        sourceLink?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkListBlock_select".
 */
export interface LinkListBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OutcomeListBlock_select".
 */
export interface OutcomeListBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        copy?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedPagesBlock_select".
 */
export interface RelatedPagesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  pages?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionNavigationBlock_select".
 */
export interface SectionNavigationBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        anchor?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock_select".
 */
export interface StatementBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  copy?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  image?: T;
  videoUrl?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock_select".
 */
export interface LeadFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  copy?: T;
  buttonLabel?: T;
  topic?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealityCheckBlock_select".
 */
export interface RealityCheckBlockSelect<T extends boolean = true> {
  heading?: T;
  copy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryEvolutionBlock_select".
 */
export interface CategoryEvolutionBlockSelect<T extends boolean = true> {
  heading?: T;
  copy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityJourneyBlock_select".
 */
export interface CapabilityJourneyBlockSelect<T extends boolean = true> {
  heading?: T;
  copy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustLogosBlock_select".
 */
export interface TrustLogosBlockSelect<T extends boolean = true> {
  heading?: T;
  copy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandIllustrationBlock_select".
 */
export interface BrandIllustrationBlockSelect<T extends boolean = true> {
  heading?: T;
  copy?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TheoryReaderBlock_select".
 */
export interface TheoryReaderBlockSelect<T extends boolean = true> {
  heading?: T;
  copy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SuccessStoriesBlock_select".
 */
export interface SuccessStoriesBlockSelect<T extends boolean = true> {
  heading?: T;
  copy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  copy?: T;
  primaryCta?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        newTab?: T;
      };
  secondaryCta?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  linkedin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  adminTitle?: T;
  title?: T;
  slug?: T;
  sourceId?: T;
  excerpt?: T;
  readingTime?: T;
  category?: T;
  authors?: T;
  publishedAt?: T;
  theme?: T;
  heroImage?: T;
  heroImageUrl?: T;
  heroImageAlt?: T;
  body?: T;
  bodyHtml?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  translationComplete?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theory-publications_select".
 */
export interface TheoryPublicationsSelect<T extends boolean = true> {
  adminTitle?: T;
  title?: T;
  version?: T;
  edition?: T;
  readingTime?: T;
  chapters?:
    | T
    | {
        slug?: T;
        title?: T;
        blocks?:
          | T
          | {
              type?: T;
              text?: T;
              lines?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  sourceProvenance?: T;
  translationComplete?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  customer?: T;
  industry?: T;
  slug?: T;
  challenge?: T;
  action?: T;
  result?: T;
  proofPoints?:
    | T
    | {
        metric?: T;
        label?: T;
        source?: T;
        id?: T;
      };
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  topic?: T;
  message?: T;
  source?: T;
  consent?: T;
  consentText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Header links, in order.
   */
  navItems?:
    | {
        label: string;
        /**
         * Legacy/fallback URL. Prefer the link field.
         */
        href?: string | null;
        link: {
          type: 'internal' | 'external';
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'publications';
                value: number | Publication;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        label: string;
        href?: string | null;
        link: {
          type: 'internal' | 'external';
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'publications';
                value: number | Publication;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  legalItems?:
    | {
        label: string;
        href?: string | null;
        link: {
          type: 'internal' | 'external';
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'publications';
                value: number | Publication;
              } | null);
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Published site-wide theme.
   */
  defaultTheme?: (number | null) | Theme;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Optional site-wide announcement. Leave empty to hide.
   */
  announcement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-settings".
 */
export interface BlogSetting {
  id: number;
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  latestHeading?: string | null;
  archiveHeading?: string | null;
  readLabel?: string | null;
  allLabel?: string | null;
  ctaHeading?: string | null;
  ctaCopy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  legalItems?:
    | T
    | {
        label?: T;
        href?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultTheme?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-settings_select".
 */
export interface BlogSettingsSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  latestHeading?: T;
  archiveHeading?: T;
  readLabel?: T;
  allLabel?: T;
  ctaHeading?: T;
  ctaCopy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}